version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: openwaiterai_db
    environment:
      POSTGRES_DB: ${OPENWAITERAI_DB_NAME}
      POSTGRES_USER: ${OPENWAITERAI_DB_USER}
      POSTGRES_PASSWORD: ${OPENWAITERAI_DB_PASSWORD}
    ports:
      - "${OPENWAITERAI_DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
