version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: openwaiterai_db
    environment:
      POSTGRES_DB: ${OPENWAITERAI_DB_NAME}
      POSTGRES_USER: ${OPENWAITERAI_DB_USER}
      POSTGRES_PASSWORD: ${OPENWAITERAI_DB_PASSWORD}
    ports:
      - "${OPENWAITERAI_DB_PORT}:5432"
    volumes:
      - openwaiterai_db_data:/var/lib/postgresql/data
      - ./01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./02_data.sql:/docker-entrypoint-initdb.d/02_data.sql

volumes:
  openwaiterai_db_data:
    driver: local
